module.exports = Object.freeze({
  account: 'clc_account',
  menus: 'clc_menus',
  periode: 'clc_periode',
  man_power: 'clc_menpower',
  man_hours: 'clc_manhours',
  head_man_power: 'clc_headmenpower',
  statistik_kecelakaan: 'clc_statistik_kecelakaan',
  inspeksi: 'clc_inspeksi',
  ach_inspeksi: 'clc_achinspeksi',
  safety_mandatory_training: 'clc_safetymandatorytraining',
  legal_spi: 'clc_legalspi',
  csms_monitoring_nbsp: 'clc_csmsmonitoringnbsp',
  proteksi_kebakaran: 'clc_proteksikebakaran_data_umum',
  proteksi_kebakaran_area: 'clc_proteksikebakaran_data_area',
  form_eval_proteksi_kebakaran: 'clc_formevalproteksikebakaran',
  resume: 'clc_resume',
  absensi_sakit: 'clc_absensi_sakit',
  absensi_safety: 'clc_absensi_safety',
  dashboardk3: 'clc_dashboardk3',
  safetymeeting: 'clc_safetymeeting',
  formevalbbsq: 'clc_formevalbbsq',
  achbsq: 'clc_achbsq',
  evalachbsq: 'clc_evalachbsq',
});
